config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'sessions/new'
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    resources :films
  end

  resources :films do
    resources :comments, only: [:create]
  end

  resources :films do
    resources :ratings, only: %i[new create]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_search
  
  def home; end
  def about; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/about.html.erb
<h1>About My Cinema Rating</h1>
<p>Наш сайт создан для...</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron" id='card-profile'>
  <div>
    <h1>Welcome to My Cinema Rating</h1>
  </div>
  
  <% unless logged_in? %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-warning" %>
    <p><h1>Already have an account</h1></p>
    <%= link_to "Log in", login_path, class: "btn btn-lg btn-success" %>
  <% else %>
    <h2>
      This is the home page for the
      <%= link_to 'My Cinema Rating', user_films_path(current_user), id: "logo" %>
    </h2>
  <% end %>
</div>

<%= render 'films/films', films: @q.result(distinct: true).where(published: true).paginate(page: params[:page], per_page: 4).order('id DESC') %>

<%# Film.all.where(published: true).paginate(page: params[:page], per_page: 4).order('id DESC')  %>