config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'sessions/new'
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    resources :films
  end

  resources :films do
    resources :comments, only: [:create]
  end

  resources :films do
    resources :ratings, only: %i[new create]
  end
end

app/models/comment.rb
# frozen_string_literal: true

# Comment model
class Comment < ApplicationRecord
  belongs_to :film, optional: true
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  include SessionsHelper
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @film = Film.find(params[:film_id])
    @comment = @film.comments.new
  end

  def create
    @film = Film.find(params[:film_id])
    @comment = @film.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.username = current_user.name
    if @comment.save
      flash[:success] = 'Comment has been created!'
      redirect_to film_path(@film)
    else
      flash[:danger] = 'Something went wrong.'
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = 'Comment has been updated!'

      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb

<div class='card'>
  <div class='body' id='card-bg'>
    <div class="form-group">
      <%= form_with model: [@film, @film.comments.build] do |form| %>
        
        <% if @film.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@film.errors.count, "error") %> prohibited this comment from being saved:</h2>
        
            <ul>
            <% @film.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
        <div>
          <%= form.text_area :body, placeholder: 'Wright a review', class: "form-control", required: true %>
        </div>
        <br>
        <div>
          <%= form.submit 'Create review', class: "btn btn-warning", method: 'get', remote: true %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<div class='container'>
  <h1>Edit Comment</h1>

  <%= form_with model: @comment do |form| %>
    <div>
      <%= form.label :body %><br>
      <%= form.text_field :body, class: "form-control" %>
      <% @comment.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <br>
    <div>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<div class='container'>
  <h1>Comments</h1>

  <ul class="list-group">
    <% @comments.each do |comment| %>
      <li class="list-group-item">
        <%= link_to comment.id, comment %> -
        <%= comment.body %>
      </li>
    <% end %>
  </ul>
  <br>
  <%= link_to 'New Comment', new_comment_path, class: 'btn btn-primary' %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <%= render 'comments/form' %>  
</div>

app/views/comments/show.html.erb
<div class='container'>
  <h1>Comment</h1>

  <h3>Id: <%= @comment.id %></h3>
  <h3>Body: <%= @comment.body %></h3>

  <%= link_to 'Delete', comment_path(@comment), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_comment_path(@comment), class: 'btn btn-primary' %>
  <br>
  <br>
  <%= link_to 'Comments', comments_path, class: 'btn btn-info' %>
</div>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>