config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'sessions/new'
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    resources :films
  end

  resources :films do
    resources :comments, only: [:create]
  end

  resources :films do
    resources :ratings, only: %i[new create]
  end
end

app/models/film.rb
# frozen_string_literal: true

# Film model
class Film < ApplicationRecord
  belongs_to :user
  has_many :ratings, dependent: :destroy
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
  validates :title, presence: true,
                    length: {
                      minimum: 3,
                      maximum: 50
                    },
                    uniqueness: { case_sensitive: false }

  before_save :fetch_film_credentials, on: :create

  # calculate the IMDb rating into stars
  def imdb_stars(imdb_rating)
    imdb = (10 - imdb_rating.to_i).to_f / 2
    5 - imdb
  end

  private

  def film_data_for_nil_response
    self.title = '---'
    self.description = 'N/A'
    # default image name 'movies-app'. Put your name here.
    self.image = ENV['DEFAULT_IMAGE']
    self.director = 'N/A'
    self.actors = 'N/A'
    self.imdb_rating = 0
  end

  def check_image(img)
    if img.match?('https')
      img
    else
      ENV['DEFAULT_IMAGE']
    end
  end

  def fetch_film_credentials
    response = ImdbService.response(CGI.escape(title))['Title']
    
    return film_data_for_nil_response if response.nil?
      
    self.title = ImdbService.response(CGI.escape(title))['Title']
    self.description = ImdbService.response(CGI.escape(title))['Plot']
    self.image = check_image ImdbService.response(CGI.escape(title))['Poster']
    self.director = ImdbService.response(CGI.escape(title))['Director']
    self.actors = ImdbService.response(CGI.escape(title))['Actors']
    self.imdb_rating = ImdbService.response(CGI.escape(title))['imdbRating']
  end
end

app/controllers/films_controller.rb
# frozen_string_literal: true

# Creates, show, update and delete articles
class FilmsController < ApplicationController
  include SessionsHelper
  before_action :find_film, only: %i[show update edit destroy]
  before_action :default_attributes, only: %i[show]
  before_action :average_rating, only: %i[show]
  before_action :require_user, only: %i[show]
  before_action :check_rating?, only: %i[show]
  before_action :set_search

  def new
    @film = current_user.films.new
  end

  def create
    @film = current_user.films.new(film_params)
    if @film.save
      redirect_to @film
    else
      render 'new'
    end
  end

  def index
    @q ||= Film.ransack(params[:q])
    @films = @q.result(distinct: true).where(published: true).paginate(page: params[:page], per_page: 8).order('id DESC')
  end

  def show; end

  def edit; end

  def update
    if @film.update(film_params)
      redirect_to @film
    else
      render 'edit'
    end
  end

  def destroy
    @film.destroy
    redirect_to films_path
  end

  private

  def film_params
    params.require(:film).permit(:title)
  end

  def find_film
    @film = Film.find(params[:id])
  end

  # fetching default attributes for film
  def default_attributes
    service = ImdbService.response(CGI.escape(@film.title))

    @img = @film.image
    @imdb = service['imdbRating'] || ''
    @votes = ImdbService.response(CGI.escape(@film.title))['imdbVotes'] || ''
    @year = service['Year'] || 'N/A'
    @runtime = service['Runtime'] || 'N/A'
    @genre = service['Genre'] || 'N/A'
    @director = service['Director'] || 'N/A'
    @actors = service['Actors'] || 'N/A'
    @country = service['Country'] || ''
    @box_office = service['BoxOffice'] || ''
    @awards = service['Awards'] || ''
    @description = service['Plot'] || ''
  end
end

app/helpers/films_helper.rb
# frozen_string_literal: true

# module helper
module FilmsHelper
  # check image for presence, if nil returns default image
  def check_image(img)
    return ENV['DEFAULT_IMAGE'] if img.nil?

    if img.match?('https')
      img
    else
      ENV['DEFAULT_IMAGE']
    end
  end

  # displays rating if voted
  def check_rating(rating)
    if rating.empty?
      content_tag :p
    else
      content_tag :div, class: 'user-rating', score: @average_rating do
        content_tag :strong, 'My Cinema Rating: '
      end
    end
  end

  # returns local time without seconds
  def show_time(time)
    Time.zone = 'Kyiv'
    local_time = Time.zone.parse(time.to_s)
    /^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}/.match(local_time.to_s)
  end
end

app/views/films/_films.html.erb
<div class='row mt-5'>
    <% films.each do |film| %>
      <div class='col-sm-3 mb-2'>
        <div class="card" id='hover'>
          <%= link_to (image_tag check_image(film.image), style: "max-height: 340px", class: "card-img-top"), film_path(film) %>
          <div class="card-body" style='height: 175px;'>
            <h5 class="card-title"><%= link_to film.title, film_path(film) %></h5>
            IMDb:<div class="rating" data-score=<%= film.imdb_stars(film.imdb_rating) %>></div>
          </div>
        </div>
      </div>
    <% end %>
</div>
<div class='flickr_pagination'>
  <%= will_paginate films %>  
</div>
<div class='footer'>
</div>

<script>
  $('.rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
          return $(this).attr('data-score');       
  }
  });
</script>

app/views/films/edit.html.erb
<div class='container'><br>
  <%= form_with(model: @film, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: 'Title' %>
    </div>
    <div class="form-group"><br>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/films/index.html.erb
<%= sort_link(@q, :imdb_rating, 'Sort by IMDb rating') %>
<%= render 'films', films: @films %>

app/views/films/new.html.erb
<div class='card'><br>
  <div class='card-header' id='card-bg'>
    <div class='form-group'>
      <%= form_with(model: @film, local: true) do |f| %>
        <div class="form-group">
          <%= f.text_field :title, placeholder: 'Title', class: 'form-control', required: true %>
        </div>
        <div class="form-group"><br>
          <%= f.submit class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/films/show.html.erb
<div class='card'>
  <div class='card-body'>
    <div class='container' id='card-bg'>
      <div class='row'>
        <div class="col-xl-4">
          <%= image_tag @film.image %>
          
          <%= check_rating(@film.ratings) %>
          votes:<%= @film.ratings.size %>  
        </div>
        <div class="col-xl-8">
          <div class="row">
            <div class="col-sm-4">
              <div>
                <strong>Title:</strong>
              </div>
              <br>
              <div>
                <strong>IMDb Rating: <%= @imdb %></strong>
              </div>
              <br>
              <br>
              <div>
                <strong>Year:</strong>
              </div>
              <br>
              <div>
                <strong>Runtime:</strong>
              </div>
              <br>
              <div>
                <strong>Genre:</strong>
              </div>
              <br>
              <div>
                <strong>Director:</strong>
              </div>
              <br>
              <div>
                <strong>Actors:</strong>
              </div>
              <br>
              <br>
              <div>
                <strong>Country:</strong>
              </div>
              <br>
              <div>
                <strong>Gross USA:</strong>
              </div>
              <br>
              <div>
                <strong>Awards:</strong>
              </div>
              <br>
              <br>
              <div>
                <strong>Description:</strong>
              </div>
            </div>
            <div class="col-sm-6">
              <div>
                <strong><%= @film.title %></strong>
              </div>
              <br>
              <div>
                <div class="imdb_rating" data-score=<%= @film.imdb_stars(@film.imdb_rating) %>></div>
                <%= @votes %> votes
              </div>
              <br>
              <div>
                <strong><%= @year %></strong>
              </div>
              <br>
              <div>
                <strong><%= @runtime %></strong>
              </div>
              <br>
              <div>
                <strong><%= @genre %></strong>
              </div>
              <br>
              <div>
                <strong><%= @film.director %></strong>
              </div>
              <br>
              <div>
                <strong><%= @film.actors %></strong>
              </div>
              <br>
              <div>
                <strong><%= @country %></strong>
              </div>
              <br>
              <div>
                <strong><%= @box_office %></strong>
              </div>
              <br>
              <div>
                <strong><%= @awards %></strong>
              </div>
              <br>
              <div>
                <%= @film.description %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @rating %>
        <%= render 'ratings/form' %>
      <% end %>
      <a href='https://www.freepik.com/vectors/background' id='bg-ancor'>Background-www.freepik.com</a>
    </div>
    <div>
      <% if current_user?(current_user) %>
        <%= render 'comments/form' %>
      <% else %>
        <p>You must logged in to leave the comments.</p>
      <% end %>
    </div>
  </div>
  <div class='card-body'>
    <div class="card-footer" id='comments'>
      <% unless @film.comments.empty?  %>
        <% @film.comments.each do |comment| %>
          <%= comment.username %><br>
          <%= comment.body %><br>
          <small class='time'><%= show_time(comment.created_at) %></small>
          <p></p>
        <% end %>
      <% else %>
        <p>There are no comments yet.</p>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('.imdb_rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
          return $(this).attr('data-score');       
  }
  });

  $('.user-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
          return $(this).attr('score');       
  }
  });
</script>