config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'sessions/new'
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    resources :films
  end

  resources :films do
    resources :comments, only: [:create]
  end

  resources :films do
    resources :ratings, only: %i[new create]
  end
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <% unless logged_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" id='header-bg'>
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                </li>
                <li class="nav-item">
                  <%= link_to "Home", root_path,id: "logo", class: 'navbar-brand' %>
                </li>
              </ul>
              <form class="d-flex">
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :title_cont, class: "form-control me-2", placeholder: 'search' %>
                  <%= f.submit 'Search', class: 'btn btn-outline-success' %>
                <% end %>
              </form>
            </div>
          </div>
        </nav>
      <% else %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" id='header-bg'>
          <div class="container-fluid">
              <%= link_to "MyCinemaRating", user_films_path(current_user), id: "logo", class: 'navbar-brand' %>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to 'Add film', new_user_film_path(current_user), id: "logo", class: 'navbar-brand' %>
                </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="logo" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <%= current_user.name %>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><%= link_to 'Profile', current_user, class:"dropdown-item" %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><%= link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %></li>
                    </ul>
                  </li>
              </ul>
              <form class="d-flex">
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :title_cont, class: "form-control me-2", placeholder: 'search' %>
                  <%= f.submit 'Search', class: 'btn btn-outline-success' %>
                <% end %>
              </form>
            </div>
          </div>
        </nav>
      <% end %>
    </header>
    <a href='https://www.freepik.com/vectors/background' id= 'bg-ancor' style='font-size: 10px;'>Background-www.freepik.com</a>

    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <div class='main-footer'>
    <br>
    <br>
    <br>
  </div>
</html>